export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const CREATE_COCKTAIL = 'CREATE_COCKTAIL';
export const CREATE_COCKTAIL_SUCCESS = 'CREATE_COCKTAIL_SUCCESS';
export const CREATE_COCKTAIL_FAILURE = 'CREATE_COCKTAIL_FAILURE';

export const GET_COCKTAILS = 'GET_COCKTAILS';
export const GET_COCKTAILS_SUCCESS = 'GET_COCKTAILS_SUCCESS';
export const GET_COCKTAILS_FAILURE = 'GET_COCKTAILS_FAILURE';

export const GET_MY_COCKTAILS = 'GET_MY_COCKTAILS';
export const GET_MY_COCKTAILS_SUCCESS = 'GET_MY_COCKTAILS_SUCCESS';
export const GET_MY_COCKTAILS_FAILURE = 'GET_MY_COCKTAILS_FAILURE';

export const GET_PUBLISHED_COCKTAILS = 'GET_PUBLISHED_COCKTAILS';
export const GET_PUBLISHED_COCKTAILS_SUCCESS = 'GET_PUBLISHED_COCKTAILS_SUCCESS';
export const GET_PUBLISHED_COCKTAILS_FAILURE = 'GET_PUBLISHED_COCKTAILS_FAILURE';

export const DELETE_COCKTAIL = 'DELETE_COCKTAIL';
export const DELETE_COCKTAIL_SUCCESS = 'DELETE_COCKTAIL_SUCCESS';
export const DELETE_COCKTAIL_FAILURE = 'DELETE_COCKTAIL_FAILURE';

export const PUBLISH_COCKTAIL = 'PUBLISH_COCKTAIL';
export const PUBLISH_COCKTAIL_SUCCESS = 'PUBLISH_COCKTAIL_SUCCESS';
export const PUBLISH_COCKTAIL_FAILURE = 'PUBLISH_COCKTAIL_FAILURE';